# 需要填写部分
center: http://127.0.0.1:12080     # 管理端地址
public_ip: 127.0.0.1            # 本级外网IP

#######################################################################
runmode: debug                     # 开发状态
#runmode: release                  # 发布状态
addr: :18001                       # 端口
name: clients                      # API server的名字
url: http://127.0.0.1:18001        # ping测试
max_ping_count: 10                 # ping次数
jwt_secret: Nu8yK8xdB8rnwgoIduJdJ6z81IdFpELKcpo1anrCw3ZGeQHrGduXXXmkB05n
log:
  writers: file,stdout             # 输出位置，有两个可选项 —— file 和 stdout
  logger_leverl: DEBUG             # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
  logger_file: log/apiserver.log
  log_format_text: false           # 日志的输出格式，JSON 或者 plaintext，true 会输出成非 JSON 格式，false 会输出成 JSON 格式
  rollingPolicy: size              # rotate 依据，可选的有 daily 和 size。如果选 daily 则根据天进行转存，如果是 size 则根据大小进行转存
  log_rotate_date: 1               # rotate 转存时间，配 合rollingPolicy: daily 使用
  log_rotate_size: 10              # rotate 转存大小，配合 rollingPolicy: size 使用
  log_backup_count: 7              # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数
work:                              # 池
  max: 10
shell:
  log: log/shell/                  # 执行命令产生的log
monitor:
  host: "0 */1 * * *"             # cron格式
  game: "0 */1 * * *"             # cron格式